services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
volumes:
  mongo_data: